Feat/navbar
AlanPinhon/deep-feels-ui pull request #13
Opened 2024-05-09 02:35 UTC by AlanPinhon

- Creación del componente `Navbar` ⚛
- Pruebas unitarias en el componente  🧪

2024-05-09 03:15 UTC, gonzalo-novak requested changes
La adición de iconos lo veo bien. El generar un navbar con esos íconos, no debería de ir aquí

2024-05-09 03:15 UTC, gonzalo-novak commented on package.json
> -    "@storybook/test": "^8.0.9",
Que bien que estes actualizando periodicamente las dependencias. De igual manera sería bueno ir actualizando las otras dependencias de manera continua (tal vez una vez a la semana, eso se puede automatizar) para evitar vulnerabilidades de seguridad u otros problemas a futuro

2024-05-09 03:15 UTC, gonzalo-novak commented on src/components/Navbar.tsx
No le veo mucho sentido a este componente. Como tal, éste debería pertencer al proyecto de deep feels y no al sistema de diseño como tal. Como podemos ver aquí, el navbar ya es un set de componentes primitivos como los Iconos que además necesita lógica como redireccionamientos

Si lo vemos desde la perspectiva del diseño atómico, el sistema de diseño en gran parte sólo debería contener átomos para que estos puedan ser usados libremente por sus consumidores. Tal vez se pueden añadir moleculas siempre y cuando no contengan lógica compleja, por ejemplo, las alertas contienen un icono y un texto, pero como tal no reciben logica compleja, sólo están listos para poder ser mostrados por el consumidor) 😄

2024-05-09 19:01 UTC, AlanPinhon commented on src/components/Navbar.tsx
Entiendo. El componente ya fue eliminado y solo quedaron las actualizaciones en cuanto a los íconos se refiere. El Nabvar será creado posteriormente en el proyecto. 🤓

2024-05-09 20:17 UTC, gonzalo-novak requested changes

2024-05-09 20:17 UTC, gonzalo-novak commented on src/assets/Icons/CompassIcon.tsx
> +    <svg data-icon='compass' width={size} height={size} onClick={onClick} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
El icono no debería contener ese tipo de props. Si necesitas añadirle interacción, sería desde el consumidor en plan:

```jsx

<div role="button" onClick={() => {}} ><CompassIcon /></div>

```

2024-05-09 20:17 UTC, gonzalo-novak commented on src/components/Icon.tsx
>    )
Es mi percepción o esta lógica fue hecha para el navbar unicamente?

2024-05-09 20:17 UTC, gonzalo-novak commented on src/assets/Icons/SettingsIcon.tsx
> +            }
Creo que esta prop no la debería de manejar el sistema de diseño, esto se puede hacer desde el consumidor si hacemos lo siguiente:

```jsx
const Icon = ({ size, ...rest }) => 
<svg stoke={(theme.theme === 'dark') ? colors.neutralColors.white : colors.purple[500]} {...rest} />
```

De esta manera, el consumidor puede sobreescribir las propiedades pre-definidas por el sistema de diseño:

```jsx
const NavBarIcon = () => {
  <Icon stroke={(selected)
              ? (theme.theme === 'dark') ? colors.neutralColors.white : colors.purple[500]
              : colors.lightPurple[500]
              }
  />
}

```

Pero lo ideal es no sobreescribir mucho los componentes desde otros proyectos. Esto lo sugiero en caso de que sea estrictamente necesario

2024-05-09 20:18 UTC, gonzalo-novak commented on src/assets/Icons/SettingsIcon.tsx
> +            }
Es más, creo que los iconos deberían siempre estar en un color neutro como negro o blanco y ya desde el consumidor darle el color deseado. Pero esto lo dejo a tu elección @AlanPinhon

2024-05-09 21:55 UTC, AlanPinhon commented on src/components/Icon.tsx
>    )
La propiedad que le había añadido para el navbar fue `selected` justo para indicar en que pantalla está el usuario.
Las propiedades  `styleVariant` y `fill` son para el corazón en cuanto a la selección de favoritos se refería.

2024-05-09 21:57 UTC, AlanPinhon commented on src/assets/Icons/SettingsIcon.tsx
> +            }
Entendido, realizaré los cambios sugeridos para no realizar demasiadas actualizaciones de propiedades.

2024-05-09 23:13 UTC, gonzalo-novak commented on src/components/Icon.tsx
>    )
Si el icono del corazón necesita un relleno, tal vez podrías añadir una prop que sea algo más explicito en plan:

```jsx
// Imagina que esto se hace desde un consumidor
<>
{ (menuItemActive) ? <Icon name="Hearth" type="solid" /> : <Icon name="Hearth" /> }
</>
```

Si el type es solid, entonces le damos relleno al icono. Si es complicado añadirle el relleno al icono de manera manual, nada más exporta la versión con relleno y sin relleno en ese mismo archivo del icono. Me imagino algo como:

```jsx
// HearthIcon.js
export const HearthIcon = () => <svg>...</svg>
export const SolidHearthIcon = () => <svg>...</svg>
```

En el componente del icon sería en plan:

```jsx 
import { HearthIcon, SolidHearthIcon } from './icons'
const Icons = {
 HearthIcon,
}
const SolidIcons = {
 HearthIcon: SolidHearthIcon
}

const Component = (props.type === 'solid' ? SolidIcons : Icons)[name];
```

Como tal, sólo son sugerencias. Lo dejo a tu criterio si optas por seguir usando el approach actual. 😄

2024-05-10 19:02 UTC, AlanPinhon commented on src/components/Icon.tsx
>    )
Ya he actualizado las propiedades del componente `Icon`. De todos modos cualquier otro comentario lo tomo en cuenta.🤓

2024-05-10 21:35 UTC, gonzalo-novak approved these changes

2024-05-10 22:43 UTC, merged