Feat/text
AlanPinhon/deep-feels-ui pull request #15
Opened 2024-05-15 00:09 UTC by AlanPinhon

Creación del componente `Text` ⚛, así como sus respectivas historias y pruebas. 🧪

2024-05-15 00:37 UTC, gonzalo-novak requested changes

2024-05-15 00:37 UTC, gonzalo-novak commented on tests/components/Text.spec.tsx
> +    const { container } = render(<Text as='nav' variant={variantText} weight={weightText} color={colors.purple[500]}>{content}</Text>)
¿Hay un caso de uso real donde tenga que darle texto a una etiqueta nav? ¿o cual es la finalidad de la prop `as`?

Adicionalmente, creo que el weightText podría ya estar pre-definido, por ejemplo, el estilo bold sería para las headings, y el estilo normal o book para los párrafos. No me imagino dandole un `weight` cada vez que necesite instanciar el componente de texto. No digo que los quites, si no más bien sería bueno poner valores por defecto ✌🏻

2024-05-15 03:52 UTC, AlanPinhon commented on tests/components/Text.spec.tsx
> +    const { container } = render(<Text as='nav' variant={variantText} weight={weightText} color={colors.purple[500]}>{content}</Text>)
Lo que pasa es que usé ésta referencia para realizar tanto el componente como para las pruebas:
https://github.com/WTTJ/welcome-ui/blob/da83126dd2654e16d8d1b5288376e3fde00d0b68/packages/Text/tests/index.test.tsx#L35

Al leerlo, entendí que, tal vez,  esa prueba la realizaron para que el cambio en la etiqueta sea efectiva al instanciar la variante de texto, independientemente si no es una etiqueta de texto.


Y en cuanto al `weight`, ¿Sería algo más o menos como lo que tienen en el sistema de Sancho UI?
https://github.com/bmcmahen/sancho/blob/82ecf45985a3dd991e1c94e23743e7ef02ef142a/src/Text.tsx#L8

De todos modos cualquier comentario lo tomo en cuenta para realizar cambios y mantener lo mejor posible el proyecto.🤓

2024-05-15 03:59 UTC, gonzalo-novak commented on tests/components/Text.spec.tsx
> +    const { container } = render(<Text as='nav' variant={variantText} weight={weightText} color={colors.purple[500]}>{content}</Text>)
Me gusta más el ejemplo que tiene sancho UI. Es un poco más limitado pero haría mas consistente el tamaño y estilo de las fuentes. Con la propiedad `as` le damos más libertad al desarrollador pero también puede que haga menos consistente la semantica del HTML. Lo que sí se me hace raro es que Sancho envuelva el body text en un div:

https://github.com/bmcmahen/sancho/blob/82ecf45985a3dd991e1c94e23743e7ef02ef142a/src/Text.tsx#L155

Pero tienen el paragraph el cual lo envuelve en una etiqueta `<p>`. Tal vez ese podría ser el valor por defecto para el componente `Text`

2024-05-16 23:19 UTC, gonzalo-novak commented on src/components/Text.tsx
> +   <StyledText as={tagName} theme={theme} color={color} variant={variant}>
¿La prop`as` sigue siendo necesario? De no ser así, ¿se podría remover? 😄

2024-05-17 04:29 UTC, gonzalo-novak approved these changes

2024-05-17 22:49 UTC, gonzalo-novak requested changes

2024-05-17 22:49 UTC, gonzalo-novak commented on tests/components/OptionMenu.spec.tsx
> -    await user.click(optionCheck);
Si ya no se piensa usar userEvent, ¿se puede remover?

2024-05-17 22:49 UTC, gonzalo-novak commented on tests/components/Icon.spec.tsx
> +    const backgroundClassName = '.sc-aYaIB'
Posiblemente tengas problemas aquí ya que los styled components tienen hashes dinamicos para las clases (si mal no recuerdo), por ende, por cada vez que se instancie el componente va a generar un hash nuevo. Tal vez se podía optar por añadir un test-id para el elemento

2024-05-17 22:51 UTC, gonzalo-novak commented on tests/components/Text.spec.tsx
> +    expect(text).toBeTruthy();
Sería mejor revisar que el texto exista en el DOM al usar el `screen.findElementByText`

2024-05-17 22:52 UTC, gonzalo-novak commented on tests/components/Text.spec.tsx
> +    expect(textVariant).toBe(variant);
Creo que esto se puede obtener si usamos el método `findElementByRole` y lo buscamos por el rol `heading`

https://testing-library.com/docs/queries/byrole/

Me causa un poco de ruido que haya un mix entre usar testing library y JS plano para obtener elementos del dom

2024-05-17 22:57 UTC, AlanPinhon commented on tests/components/OptionMenu.spec.tsx
> -    await user.click(optionCheck);
De hecho lo quité y quité la importación.

2024-05-17 22:59 UTC, gonzalo-novak commented on tests/components/OptionMenu.spec.tsx
> -    await user.click(optionCheck);
Lo sigo viendo instalado en el proyecto:

https://github.com/AlanPinhon/deep-feels-ui/pull/15/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R30

2024-05-17 23:45 UTC, gonzalo-novak requested changes

2024-05-17 23:45 UTC, gonzalo-novak commented on tests/components/Text.spec.tsx
> +    const textVariant = getByRole('heading', {level: 1}) as HTMLHeadElement;
¿No sería mejor buscarlo por el texto? en plan:

```suggestion
    const textVariant = getByRole('heading', {name: content}) as HTMLHeadElement;
```

2024-05-17 23:45 UTC, gonzalo-novak commented on tests/components/Text.spec.tsx
> +    const { getByRole } = render(<Text variant={variant} color={colors.purple[500]}>{content}</Text>)
¿Hay alguna ventaja sobre este approach en vez de usar `screen.getByRole`?

https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#not-using-screen

2024-05-18 00:29 UTC, gonzalo-novak approved these changes

2024-05-18 20:04 UTC, merged