Refactor/Alert-Text
AlanPinhon/deep-feels-ui pull request #20
Opened 2024-06-01 03:15 UTC by AlanPinhon

Refactorizaciones de código en los componentes `Alert` y `Text`

2024-06-01 03:40 UTC, gonzalo-novak requested changes

2024-06-01 03:40 UTC, gonzalo-novak commented on src/components/Alert.tsx
> +  icon?: 'CheckIcon' | 'ErrorIcon';
¿No sería mejor hacer referencia directa a los types del icon? en plan:

`IconType['CheckIcon'] | IconType['ErrorIcon']`

2024-06-01 03:40 UTC, gonzalo-novak commented on src/components/Alert.tsx
> +        margin='0 0 0 .5rem'
Siento que sería mejor exponer todo la propiedad del style por si necesitamos customizar el estilo del componente. Otra opión es que envuelvas el text en un div y le des ese margin al div

2024-06-04 07:11 UTC, AlanPinhon commented on src/components/Alert.tsx
> +  icon?: 'CheckIcon' | 'ErrorIcon';
Al hacer referencia de esa forma no me da los opciones de los nombres. Me apoyé en Chat GPT y me dio la sugerencia de utilizar `Extract` para filtrar los valores, ya que `IconName `es un tipo de unión de cadenas y no un objeto. Me dio otra opción de utilizar `enum` pero siento que es más relajo.

2024-06-04 07:18 UTC, AlanPinhon commented
De momento hice los cambios solicitados y en cuanto a manejar la duración de la visibilidad, terminé haciendo el manejo del estado en cuanto a la clase se refiere. Anteriormente lo hice mediante una propiedad booleana "visible", pero al correr las pruebas (que aún no están actualizadas en el repositorio por lo mismo) me aparece un warning que dice que se está pasando un valor booleano en una propiedad "no-booleana" y que pase el valor de `boolean` a `string`.

Ejemplo: de `visible=true` a `visible="true"`.

Entonces de momento solo quiero checar si esta solución es la más viable para manejar la visibilidad de la alerta. De todos modos cualquier comentario u observación estoy abierto a tomarla en cuenta. 🤓

2024-06-04 18:14 UTC, gonzalo-novak approved these changes

2024-06-04 20:39 UTC, merged