feat: context created for app color theme
AlanPinhon/deep-feels-ui pull request #4
Opened 2024-04-06 00:50 UTC by AlanPinhon

Creación del contexto para manejar el tema de color en los componentes y la aplicación. ☀🔄🌙

2024-04-06 01:01 UTC, gonzalo-novak approved these changes

2024-04-06 01:01 UTC, gonzalo-novak commented on src/components/Button.tsx
>    variant: string,
Sugiero que las variantes tengan los posibles valores en vez de dejarlo como un string:

```suggestion
  variant: 'primary' | 'error' | 'feelings',
```

2024-04-06 01:01 UTC, gonzalo-novak commented on src/components/Button.tsx
> +    </ThemeProvider>
No creo que sea buena idea envolver el `ThemeProvider` por cada componente. Normalmente el provider se deja a discreción del desarrollador para importarlo por proyecto. Tal vez necesites utilizar el hook `useTheme` nada más.

Veo que en Sancho UI exponen el provider por story: https://github.com/bmcmahen/sancho/blob/master/.storybook/config.js#L3

2024-04-06 01:02 UTC, gonzalo-novak requested changes
Dejé unos comments, sólo que le di "approve" sin querer xD

2024-04-07 20:13 UTC, AlanPinhon commented on src/components/Button.tsx
> +    </ThemeProvider>
Tienes razón. Solo con el uso del hook `useTheme` fue más que suficiente. Ya están los cambios actualizados. 🔄

2024-04-08 05:56 UTC, gonzalo-novak approved these changes

2024-04-08 18:48 UTC, merged