feat: InputForm component created
AlanPinhon/deep-feels-ui pull request #5
Opened 2024-04-09 00:27 UTC by AlanPinhon

Creación del componente `InputForm` en sus temas claro y oscuro. ✒

2024-04-09 01:45 UTC, gonzalo-novak requested changes
Adicionalmente, si tienes pensado abrir un PR por nuevo componente, sugiero que también añadas sus tests unitarios y no dejarlo al final 😅

2024-04-09 01:45 UTC, gonzalo-novak commented on src/components/InputForm.tsx
> +      <StyledInputForm theme={theme} type={type} variant={variant} placeholder={placeholder}/>
Mi única duda es cómo vas a manejar el estado del input, o con base al diseño, ¿no es necesario?

Me puse a pensar en el caso en donde escribo algo y el estado del input necesite cambiar a un error o viceversa 🤔

2024-04-09 01:45 UTC, gonzalo-novak commented on src/theme/theme.ts
> +  },
Hasta apenas me doy cuenta que los colores por cada componente tiene su propiedad en el theme con su respectiva configuración de colores + colores hardcodeados. Creo que los colores no deberían estar atados a los estilos de cada componente. De otra manera, esto me dice que el sistema de diseño puede que no sea consistente al 100%

2024-04-11 18:16 UTC, gonzalo-novak requested changes
Generar un componente input parece sencillo pero puede llegar a ser un dolor de cabeza. Sugiero que te ayudes de ChatGPT para ir conociendo cómo normalmente se generan este tipo de componentes para un sistema de diseño. Normalmente estos componentes suelen ser "tontos" sin tener algún tipo de lógica compleja (la mayoría de las veces)

2024-04-11 18:16 UTC, gonzalo-novak commented on src/components/InputForm.tsx
> +  color: #F04C4C
¿Este color no tendría que venir del theme? O ese cambio irá en el otro PR que mencionaste?

2024-04-11 18:16 UTC, gonzalo-novak commented on src/components/InputForm.tsx
> +    if(inputType === 'text') return /^[a-zA-ZÀ-ÿ\s]{3,40}$/.test(inputValue);
Las validaciones son a discreción del desarrollador; no se deberían hardcodear validaciones en un componente

2024-04-11 18:16 UTC, gonzalo-novak commented on src/components/InputForm.tsx
> +      {errorMsg && <StyledErrorMsg>{errorMsg}</StyledErrorMsg>}
Eso está bien, sólo el componente debe saber si el `errorMsg` existe, pero los cambios de estado los hará el desarrollador, no el componente como tal. Recomiendo que veas algunos ejemplos de como se crean los inputs en otros sistemas de diseño, tal vez Sancho UI o algun otro repo de código abierto tenga otros ejemplos. 

Hay algunos repos como:
- [Adobe react spectrum](https://github.com/adobe/react-spectrum/blob/main/packages/react-aria-components/src/Input.tsx)
- [Ant design ](https://github.com/ant-design/ant-design/blob/master/components/input/Input.tsx)

Sin embargo, esos ejemplos son algo complejos. Tal vez puedes ayudarte de ChatGPT para que te des una idea de cómo se generaría un componente Input más sencillo

2024-04-11 18:16 UTC, gonzalo-novak commented on src/theme/theme.ts
> +      border: "#B7E9A0",
Siento que vas a hacer mucho re trabajo si no corriges lo de los colores primero 🧛🏻

2024-04-11 18:16 UTC, gonzalo-novak commented on tests/components/InputForm.spec.tsx
> +    expect(screen.getByText('Enter a valid email')).toBeTruthy();
Siento que los tests no reflejan un uso real del input, en teoría el desarrollador debería tener la habilidad de usar un useState para controlar dicho input 🐰

2024-04-11 18:33 UTC, AlanPinhon commented on src/components/InputForm.tsx
> +  color: #F04C4C
De momento lo había dejado así para mostrar el mensaje de error. En el otro PR ya ira especificado desde el `theme`.

2024-04-14 01:03 UTC, AlanPinhon commented
He realizado los cambios en el código en cuanto al color y tema se refieren. Basándome en el diseño atómico, actualicé también el componente del `input` para dejarlo más simple. Así mismo, tomando como referencia esta prueba ( https://github.com/vimeo/iris/blob/main/src/components/inputs/Input/Input.test.tsx ) y el comentario que me dejaste actualicé la prueba del mismo `input`. Me ayudé de ChatGPT también para realizar los cambios. Cualquier comentario estoy pendiente. 🦅

2024-04-14 02:27 UTC, gonzalo-novak requested changes
Dejé un par de comentarios. Avisame si tienes alguna duda 😄

2024-04-14 02:27 UTC, gonzalo-novak commented on src/theme/theme.ts
> +    successBorder: interfaceColors.border.success.light,
Siento que ahora mi pregunta es la siguiente: ¿por qué deberíamos exponer estos colores en el context si estos pueden ser referenciados en los estilos del propio componente? 

Es decir, ¿por qué no usar los colores del sistema de diseño directamente en los estilos del componente en su respectivo archivo? 🐘 

En teoría los colores del sistema de diseño són los que deberían de ir expuestos en el context para ser usados en los componentes en plan:

```tsx
// MiBoton.tsx

const MiBoton = () => {
 const theme = useTheme();
 const ButtonComponent = style.button`
    background-color: ${
      //El objecto colors debería de arrojar los valores para el tema seleccionado: 
      //si el tema es claro, arrojo automaticamente el color rojo para el tema claro y lo mismo para el modo oscuro
      // la propiedad `200` es el nivel de intensidad del color:  https://tailwindcolor.com/ <- Es solo un ejemplo
      props => (props.variant === 'error') && props.theme.colors.red['200']
    } 
 `
 return <ButtonComponent theme={theme}>
}
```

Es más o menos como yo lo veo, pero no espero que hagas lo que yo digo; Sólo revisa bien el approach para que sea más sencillo de mantener ;D

2024-04-14 02:58 UTC, gonzalo-novak commented
> He realizado los cambios en el código en cuanto al color y tema se refieren. Basándome en el diseño atómico, actualicé también el componente del `input` para dejarlo más simple. Así mismo, tomando como referencia esta prueba ( https://github.com/vimeo/iris/blob/main/src/components/inputs/Input/Input.test.tsx ) y el comentario que me dejaste actualicé la prueba del mismo `input`. Me ayudé de ChatGPT también para realizar los cambios. Cualquier comentario estoy pendiente. 🦅


Siento que más bien un test para estos componentes sería algo así:

```tsx

describe("Input Tests", () => {

 it("should show an error message", async () => {
 const InputErrorTest = () => {
   const [value, setValue] = useState("");
   const [errMsg, setErrMsg] = useState("";
   
   const handleOnChange = (e) => {
     setValue(e.value)
     if (!e.value) setErrMsg("Ta' vacia esta mae")
     
   }
   
   return (
      <>
       <Input value={value} onChange={handleOnChange}/>
       {Boolean(errMsg) && errMsg}
     </>
   )
 }

 const user =  userEvent.setup() 
 render(<InputErrorTest />)
 
 const inputEl = await screen.findByTestId("input-testid")
 user.type(inputEl, "Hello")
 expect(screen.queryByText("Ta' vacia esta mae")).not.toBeInTheDOM()
  user.type(inputEl, "") // <- No recuerdo como dejar el input vacio
   expect(await screen.findByText("Ta' vacia esta mae")).toBeInTheDOM()
 })
})

```

2024-04-17 02:09 UTC, gonzalo-novak approved these changes

2024-04-17 02:09 UTC, gonzalo-novak commented on src/theme/colors.ts
> +  r_950: '#1C0202',
No me convence del todo poner un prefijo `r_[intensidad_de_color]` ya que en sí accederíamos como

`theme.color.red['200']`

Y acceder en plan:

`theme.color.red['r_200']` 

Se mira algo redundante. Pero siento que tampoco es un blocker; veamos como funciona con el approach actual

2024-04-17 18:10 UTC, merged